apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-green
  namespace: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
      version: green
  template:
    metadata:
      labels:
        app: sample
        version: green
  spec:
    containers:
    - name: sample
      image: vaibhavverma07/used-cars:v2
      ports:
      - containerPort: 80